### ISSUE TITLE
[mongo] Plugin does not pick up mongo containers after selecting the environment 

### ISSUE THREAD

**Issue by akarasulu** [subutai-attic/peer-os-plugins#113]
I installed the mongo plugin then created the following 3 container environment called mongo-test:

<img width="1137" alt="screen shot 2016-10-29 at 9 30 45 pm" src="https://cloud.githubusercontent.com/assets/10051386/19833847/24c2dc5a-9e1f-11e6-9e81-ef0c65d4c6d5.png">

I select the mongo-test environment after launching the plugin and none of the containers are available to assign to cluster node types:

<img width="1119" alt="screen shot 2016-10-29 at 9 30 05 pm" src="https://cloud.githubusercontent.com/assets/10051386/19833851/4c2c0708-9e1f-11e6-8bff-091fa6020708.png">

**Comment by dilshat** [comment]
Can you try with template **mongo32** template, @akarasulu ?
Seems this is the template to use. @eabyshev we should somehow let users know what template to use or delete **mongo** and rename **mongo32** to **mongo**.

**Comment by dilshat** [comment]
Working with **mongo32** template

![image](https://cloud.githubusercontent.com/assets/3367326/19834554/8d83b0b0-9e8e-11e6-8119-4c4a678668f2.png)

**Comment by dilshat** [comment]
Also works if using plugin helper
![image](https://cloud.githubusercontent.com/assets/3367326/19834561/b6c77916-9e8e-11e6-95aa-8c77d6568e4e.png)

**Comment by eabyshev-zz** [comment]
Renamed all templates without version suffix.
