### ISSUE TITLE
Plugin upload form allows empty fields

### ISSUE THREAD

**Issue by tzununbekov** [subutai-attic/peer-os-plugins#122]
Need to add filed check to plugin upload form in SS because now I can upload "undefined" plugins:

![image](https://cloud.githubusercontent.com/assets/13515865/20696813/0daa37de-b620-11e6-956f-13e9b29f43bf.png)

**Comment by eabyshev-zz** [comment]
Fixed.

**Comment by tzununbekov** [comment]
Space bar in fields passes checks but gives the same result as empty fields

![image](https://cloud.githubusercontent.com/assets/13515865/20738826/5229c378-b6e0-11e6-8394-a5783f9aadec.png)

Clicking "edit" on those items gives me following:

![image](https://cloud.githubusercontent.com/assets/13515865/20738881/a94e1f3c-b6e0-11e6-855d-f3bad555e324.png)

**Comment by eabyshev-zz** [comment]
@tzununbekov fixed, please check.
