### ISSUE TITLE
Remove usage of EnvironmentManager#addReverseProxy

### ISSUE THREAD

**Issue by dilshat** [subutai-attic/peer-os-plugins#132]
Use Peer#addCustomProxy, Peer#removeCustomProxy in all plugins instead of EnvironmentManager#addReverseProxy. This method is deprecated.

**Comment by akarasulu** [comment]
I would just remove the deprecated call after a search for it in the code base. We don't have users using the API right now so we can do this without deprecation practices right now. Tomorrow that will change of course when we have to deal with a community of users.
