### ISSUE TITLE
Got timeout error, when tried to create cassandra cluster

### ISSUE THREAD

**Issue by soffokl** [subutai-attic/peer-os-plugins#144]
![image](https://cloud.githubusercontent.com/assets/8612618/22418689/48dd13fc-e704-11e6-8200-3a66788d6b93.png)
[karaflogs2017-01-30 15-52-04.txt](https://github.com/subutai-io/plugins/files/738542/karaflogs2017-01-30.15-52-04.txt)

**Comment by soffokl** [comment]
Another try gave following:
![image](https://cloud.githubusercontent.com/assets/8612618/22419655/b615336a-e708-11e6-8d6d-653467b3b9fc.png)

**Comment by dilshat** [comment]
Done
