### ISSUE TITLE
[AppScale] Selecting a container on a remote peer doesn't set the revproxy configs

### ISSUE THREAD

**Issue by asanaliev** [subutai-attic/peer-os-plugins#25]
**Steps to reproduce:**
1. On SS itself (w/o Hub) build cross-peer environment with AppScale template: two peers; one container each.
2. On Peer A, open the AppScale plugin and select as the controller a container on Peer B. Example: 6c33..., on the image below.
3. Install AppScale cluster. 

![appscale](https://cloud.githubusercontent.com/assets/7465404/14366544/fe27bd4e-fd34-11e5-9e52-1055a5b4c79c.gif)

**Result:**
The cluster is installed successfully but the AppScale console is not accessible. This is b/c the plugin sets the revproxy configs if the controller is on Peer A only. In general, where the plugin is opened. If a controller is on a remote peer, there is no revproxy configs. For example, there are no revproxy files on both peers:
`/var/lib/apps/subutai/current/nginx-includes`

Also karaf logs on Peer A shows this error:
`2016-04-07 20:49:28,187 | ERROR | pool-93-thread-2 | ClusterConfiguration             | 286 - io.subutai.plugin.appscale.impl - 4.0.0.RC7 | io.subutai.common.peer.HostNotFoundException: Container host not found by id 4591D3204E4A1300FFCD9C0E6573598A0DB43831 ()`

**Comment by eabyshev-zz** [comment]
done
