### ISSUE TITLE
[Zookeeper] Wrong message about Hadoop cluster requirement

### ISSUE THREAD

**Issue by asanaliev** [subutai-attic/peer-os-plugins#46]
_Minor issue._

I created a new environment with three templates of Zookeeper. When I open the Zookeeper plugin it gives this error:

![image](https://cloud.githubusercontent.com/assets/7465404/15807876/5cfd671e-2b8a-11e6-81ef-76ae8862f2a4.png)

Zookeeper can be install without Hadoop too, and I could do that. This error message is redundant. 
# 

My SS:
![image](https://cloud.githubusercontent.com/assets/7465404/15807888/8efc0f2c-2b8a-11e6-808c-8e205816db56.png)

**Comment by eabyshev-zz** [comment]
done
