### ISSUE TITLE
[UserGrid] Can't see all containers if installed on x-peer 

### ISSUE THREAD

**Issue by asanaliev** [subutai-attic/peer-os-plugins#49]
I created an environment for UserGrid on two peers: one with Cassandra, another with Tomcat and Elastisearch.  

![image](https://cloud.githubusercontent.com/assets/7465404/15808381/975c3864-2b98-11e6-8029-b04b21588e5e.png)

But I don't see all containers in the UserGrid plugin:

![image](https://cloud.githubusercontent.com/assets/7465404/15808384/a62540fc-2b98-11e6-9e9f-151d8a376f29.png)

**Comment by eabyshev-zz** [comment]
In my case I can create cluster. Seems problem of chosen templates. There should be tomcat7, cassandra, elasticsearch144.
