### ISSUE TITLE
[Spark] Failed to install on x-peer

### ISSUE THREAD

**Issue by asanaliev** [subutai-attic/peer-os-plugins#52]
I created a Hadoop cluster on x-peer: two peers, two Hadoop containers each. 

![image](https://cloud.githubusercontent.com/assets/7465404/15808947/6c50255a-2ba6-11e6-9cdb-61eb8a79e757.png)

Installing a Spark cluster over it:

![image](https://cloud.githubusercontent.com/assets/7465404/15808956/99189b58-2ba6-11e6-9d7d-2cd8ee615fe1.png)

But installation is in progress and doesn't complete.

![image](https://cloud.githubusercontent.com/assets/7465404/15808979/853e5d42-2ba7-11e6-9bf4-0a6052e0b892.png)

I tried three times, always with same result.

**Comment by asanaliev** [comment]
Finally, I succeeded to install. On x-peer, installation may take more that 5 min. Although on single peer it takes less than a couple of minutes.

**Comment by eabyshev-zz** [comment]
@asanaliev, this is because of, executing apt-get install before each over hadoop product installation, it downloading deb file.
