### ISSUE TITLE
[UserGrid] Old environments were not deleted from DB

### ISSUE THREAD

**Issue by samsonbek** [subutai-attic/peer-os-plugins#60]
I have only one environment created with UserGrid template
![image](https://cloud.githubusercontent.com/assets/4163679/16406200/915a8d38-3d2e-11e6-85f7-fdd17d778d27.png)

but after installing UserGrid cluster, when i try to manage cluster, it shows me several environments, all of them are deleted, except current one env.
![image](https://cloud.githubusercontent.com/assets/4163679/16406259/f819064e-3d2e-11e6-9bcf-d3f732489bc8.png)

**Comment by dilshat** [comment]
Is environment deleted from Hub?

**Comment by samsonbek** [comment]
@Dilshat yes, in environment list there is only one new environment, but in select list it show old deleted environments also.

**Comment by samsonbek** [comment]
seems UserGrid plugin stores environment IDs in separate place, and when environment is deleted, it's ID not deleted from that place

**Comment by eabyshev-zz** [comment]
done
